version: '2'
services:
  backend:
    container_name: jewels-springboot
    build:
      context: .
      dockerfile: Dockerfile
    image: jewels-springboot:latest
    ports:
      - 5001:5001
    volumes:
      - backend_data:/opt/serving/
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/ecommerce
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: jewels
    depends_on:
      - database
    networks:
      - cloud-network
    restart: always

  frontend:
    container_name: jewels-reactjs
    build:
      context: jewels-reactjs
      dockerfile: Dockerfile
    image: jewels-reactjs:latest
    ports:
      - 5000:5000
    networks:
      - cloud-network
    restart: always

  database:
    container_name: jewels-postgres
    image: postgres:16
    environment:
      POSTGRES_DB: ecommerce
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: jewels
    ports:
      - 5432:5432
    networks:
      - cloud-network
    restart: always

networks:
  cloud-network:
    driver: bridge

volumes:
  backend_data:

